[project]
name = "tfl_api_app"
requires-python = ">=3.11.1"
dynamic = [ "version" ]
dependencies = [
    "coverage",
    "matplotlib",
    "numpy",
    "pandas",
    "pydantic>=2.12.5",
    "requests",
    "seaborn",
    "tenacity",
]
optional-dependencies = { dev = ["black", "ipykernel", "ruff", "pytest"] }

[tool.black]
line-length = 120
target-version = ['py312']
extend-exclude = ".ipynb"

[tool.ruff]
line-length = 120
lint.select = ["E", "F", "I"]
lint.ignore = ["E203"]
exclude = [ "**/*.ipynb" ]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.coverage.report]
show_missing = true
fail_under = 80
skip_covered = true
exclude_lines = [
    "if __name__ == __main__:",
]

[tool.coverage.run]
omit = [ "**/__init__.py" ]
source = [ "src/" ] 