[tox]
envlist = format, lint, test
skip_missing_interpreters = true

[testenv]
base_python = 3.11
set_env = 
    TFL_ACCESS_KEY = {env:TFL_ACCESS_KEY}
passenv = TFL_ACCESS_KEY
deps = -e .[dev]

[testenv:format]
description = Automatically format with black
commands = 
    black --check .

[testenv:lint]
description = Automatically lint code with ruff
commands =
    ruff check .

[testenv:type]
description = Run type checking using mypy
deps = 
    mypy==1.11.0
commands =
    mypy src --install-types --non-interactive

[testenv:test]
description = Run unit tests and output coverage report
commands =
    coverage run -m unittest discover -s tests
    coverage report -m